// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ASelect: typeof import('ant-design-vue/es')['Select']
    CesiumMap: typeof import('./src/components/CesiumMap.vue')['default']
  }
}

export {}
